name: release and deploy

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      # Setup Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Install xmllint
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      # Set git user name and email
      - name: Set up Git
        run: |
          chmod +x ci/setup-git.sh
          ci/setup-git.sh
      # Release, set correct versions and create tag
      - name: Release (versioning/tag)
        run: |
          chmod +x ci/mvn-release.sh
          ci/mvn-release.sh

  deploy-release:

    needs: release
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      # Setup Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven setup
        uses: ./.github/actions/mvn-setup
        with:
          mgnl_nexus_user: ${{secrets.MGNL_NEXUS_USER}}
          mgnl_nexus_pass: ${{secrets.MGNL_NEXUS_PASS}}
      # Run maven verify
      - name: Maven verify
        run: mvn verify --batch-mode
      # Publish
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
