name: verify

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven setup
        uses: ./.github/actions/mvn-setup
        with:
          mgnl_nexus_user: ${{secrets.MGNL_NEXUS_USER}}
          mgnl_nexus_pass: ${{secrets.MGNL_NEXUS_PASS}}
      # Run maven verify
      - name: Maven verify
        run: mvn verify --batch-mode