name: verify (6_2)

on:
  push:
    branches-ignore:
      - main-6_2

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Maven setup
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "magnolia.enterprise.group",
              "username": "${{secrets.MGNL_NEXUS_USER}}",
              "password": "${{secrets.MGNL_NEXUS_PASS}}"
            }]
      - name: Maven verify
        run: mvn verify --batch-mode
